Controllers/AdvancedChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using SignalRSample.Data;
using SignalRSample.Hubs;
using SignalRSample.Models.ViewModel;
using System.Security.Claims;

namespace SignalRSample.Controllers
{
    public class AdvancedChatController : Controller
    {
        private readonly ILogger<AdvancedChatController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IHubContext<AdvancedChatHub> _hub;

        public AdvancedChatController(ILogger<AdvancedChatController> logger, ApplicationDbContext context, IHubContext<AdvancedChatHub> hub)
        {
            _logger = logger;
            _context = context;
            _hub = hub;
        }

        [Authorize]
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ChatViewModel chatViewModel = new()
            {
                Rooms = _context.ChatRoom.ToList(),
                MaxRoomsAllowed = 4,
                UserId = userId,
            };

            return View(chatViewModel);
        }
    }
}

Controllers/SuperAdvancedChatController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using SignalRSample.Data;
using SignalRSample.Hubs;
using SignalRSample.Models.ViewModel;
using System.Security.Claims;

namespace SignalRSample.Controllers
{
    public class SuperAdvancedChatController : Controller
    {
        private readonly ILogger<AdvancedChatController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly IHubContext<AdvancedChatHub> _hub;

        public SuperAdvancedChatController(ILogger<AdvancedChatController> logger, ApplicationDbContext context, IHubContext<AdvancedChatHub> hub)
        {
            _logger = logger;
            _context = context;
            _hub = hub;
        }

        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            ChatViewModel chatViewModel = new()
            {
                Rooms = _context.ChatRoom.ToList(),
                MaxRoomsAllowed = 4,
                UserId = userId,
            };

            return View(chatViewModel);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SignalRSample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SignalRSample.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SignalRSample</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Notification">Notification</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="DeathlyHallowRace">Deathly Hallow Race</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="HarryPotterHouse">Harry Potter House</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="BasicChat">Basic Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdvancedChat" asp-action="Index">Advanced Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SuperAdvancedChat" asp-action="Index">Super Advanced Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Order">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="OrderList">Order List</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SignalRSample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="//cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PrivateChat.cshtml
@model SignalRSample.Models.ViewModel.ChatViewModel

<div style="height:450px;">
     <div class="h-100 row" style="overflow: hidden;">
            <div class="col-md-4 col-6">
                <div class="h-100 p-2" style="background-color:#e6e9f0">
                <div class="h-100 rounded border border-dark" style="overflow: hidden;">
                    <div  style="overflow-y:auto; max-height:400px">  
                        <input type="hidden" id="hdchatUserId" value="" />

                        <div class="list-group p-2" id="list-tab" role="tablist">    
                            

                        @*<input type="hidden" id="hdchatUserId" value="@(Model.Input.Users.Any() ? Model.Input.Users.First().Id : "")" />
                        @foreach(var item in Model.Input.Users)
                        {
                            <a class="list-group-item list-group-item-action @(Model.Input.Users.First().Id == item.Id ? "active" : "")" id="list-@(item.Id)-list" 
                                            data-bs-toggle="list" href="#list-@(item.Id)" role="tab" onclick="setchatuserId('@item.Id')" aria-controls="list-@(item.Id)">
                                <div class="row">
                                    <div class="col"> 
                                        @item.UserName
                                    </div>
                                    <div class="col-auto"> 
                                        <i class="block-text align-middle bg-success rounded-circle d-none"
                                            id="spanOnline@(item.Id)" style="margin-left:5px;" title="Online">
                                            </i>  
                                    </div>
                                </div>
                                                   
                             </a>

                                            
                                             
                        }*@
                        </div>
                    </div>
                </div>
                </div>
            </div>
            <div class="col-md-8 col-6">
                <div class="rounded h-100" style="background-color:#e6e9f0">
                    <div class="row h-100 flex-column" style="overflow:hidden;">
                        <div class="d-flex flex-fill pt-3 px-4">
                           <div class="d-block border border-dark rounded w-100 h-100" >                           
                                   <div class="tab-content" id="nav-tabContent" >
                        
                                        @*@foreach(var item in Model.Input.Users)
                                        {
                                            <div class="tab-pane fade @(Model.Input.Users.First().Id == item.Id ? "show active" : "")" id="list-@(item.Id)" role="tabpanel" aria-labelledby="list-@(item.Id)-list">
                                            
                                                <div style="overflow: hidden;"> 
                                                    <div class="d-block px-2 pb-2"  style="overflow-y:auto; max-height:360px">  
                                                        <ul style="list-style-type:none;" id="ulmessagesList@(item.Id)">
                                                             
                                                        </ul>
                                                    </div>
                                                </div>
                                                 

                                            </div>
                                        }   *@

                        
                                    </div>  
                           </div>
                       </div>
                       <div class="d-flex flex-column p-4">
                            <div class="row align-items-center">
                                    <div class="col-auto">
                                    <label for="inputMessagePrivate" class="col-form-label">Message</label>
                                    </div>
                                    <div class="col">
                                        <input type="text" id="inputMessagePrivate" onkeyup="readyprivateMessage()" class="form-control">
                                    </div>
                                    <div class="col-auto">
                                        <button type="button" disabled 
                                        id="btnMessagePrivate"
                                        onclick="sendprivateMessage()" 
                                        class="btn btn-primary">Send</button>
                                    </div>

                                </div>
                        </div>
                  
                    </div>
                </div>
            </div>
        </div>          
                 
</div>

Views/Shared/_PublicChat.cshtml
@model SignalRSample.Models.ViewModel.ChatViewModel
<ul class="nav nav-tabs" style="background-color:#e6e9f0"  role="tablist" id="ulroomTabs">
    @foreach(var item in Model.Rooms){

    <li class="nav-item w-25" role="presentation">
        <a class="nav-link text-center @( Model.Rooms.First().Id == item.Id ? "active" : "")" id="room@(item.Id)-tab" data-bs-toggle="tab" 
            href="#room@(item.Id)" role="tab" aria-controls="room@(item.Id)" aria-selected="true">
            @item.Name <i class="bi bi-trash text-danger deleteRoom" onclick="deleteRoom(@item.Id,'@item.Name')"></i>
        </a>
    </li>
    }
@if (Model.AllowAddRoom)
    {
        <li class="nav-item w-25" disabled id="liaddnewRoom" onclick="addnewRoom(@Model.MaxRoomsAllowed)" role="presentation">
            <a class="nav-link text-center @(Model.Rooms.Any() ? "" : "active")" data-bs-toggle="tab" 
                href="#" role="tab" aria-controls="roomAdd" aria-selected="true">
                <i class="bi bi-plus-lg bg-white text-black px-2"></i>
            </a>
        </li>
}
</ul>
                <div class="tab-content" style="height:400px;background-color:#fff;" id="divRooms">
                    @foreach(var item in Model.Rooms){
                        <div class="tab-pane h-100 fade @(Model.Rooms.First().Id == item.Id ? "show active" : "")" id="room@(item.Id)" role="tabpanel" aria-labelledby="room@(item.Id)-tab">
                            <div class="container  h-100" >
                                <div class="row h-100 flex-column p-3">                              

                                    <div class="flex-fill border border-dark rounded" style="overflow:hidden;">
                                        <div class="d-block"  style="overflow-y:auto; max-height: 280px"> 
                                            <ul class="p-2" style="list-style-type:none;" id="ulmessagesList@(item.Id)">

                                            </ul>
                                        </div>
                                    </div>

                                    <div class="flex-column">
                                        <div class="row py-3">
                                                <div class="col-auto">
                                                <label for="inputMessage@(item.Id)" class="col-form-label">Message</label>
                                                </div>
                                                <div class="col">
                                                <input type="text" id="inputMessage@(item.Id)" onkeyup="readypublicMessage(@item.Id)" class="form-control">
                                                </div>
                                                <div class="col-auto">
                                                    <button type="button" disabled 
                                                    id="btnMessage@(item.Id)"
                                                    onclick="sendpublicMessage(@item.Id)" 
                                                    class="btn btn-primary">Send</button>
                                                </div>
                                            </div>                                             
                                    </div>
              
                                </div>
                            </div>
                        </div>
                    }
                </div>

Views/Shared/_PublicChatlight.cshtml
@model SignalRSample.Models.ViewModel.ChatViewModel

  <ul class="nav nav-tabs"  style="background-color:#e6e9f0"  role="tablist" id="ulroomTabs">
        @foreach(var item in Model.Rooms){

        <li class="nav-item  w-25" role="presentation">
            <a class="nav-link text-center @( Model.Rooms.First().Id == item.Id ? "active" : "")" id="room@(item.Id)-tab" data-bs-toggle="tab" 
                href="#room@(item.Id)" role="tab" aria-controls="room@(item.Id)" aria-selected="true">
                @item.Name
            </a>
        </li>
        }
                    
    </ul>
    <div class="tab-content" style="height:470px;background-color:#fff" id="divRooms">
        @foreach(var item in Model.Rooms){
            <div class="tab-pane h-100 fade @(Model.Rooms.First().Id == item.Id ? "show active" : "")" id="room@(item.Id)" role="tabpanel" aria-labelledby="room@(item.Id)-tab">
                <div class="container  h-100" >
                    <div class="row h-100 flex-column p-3">                              

                        <div class="flex-fill border border-dark rounded" style="overflow:hidden;">
                            <div class="d-block"  style="overflow-y:auto; max-height: 450px"> 
                                <ul class="p-2" style="list-style-type:none;" id="ulmessagesList@(item.Id)">

                                </ul>
                            </div>
                        </div>

                                    
                    </div>
                </div>
                @*<div class="d-flex p-3 h-100" style="background-color:#fff" >                              
                   
                    <div class="flex-fill border border-dark" style="overflow: hidden;">
                        <div class="d-block"  style="overflow-y:auto; max-height: 450px"> 
                            <ul class="p-2" style="list-style-type:none;" id="ulmessagesList@(item.Id)">

                            </ul>
                        </div>
                    </div>                                       
              
                </div>*@
            </div>
        }
    </div>